### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by impredicative** [twintechlabs/iomodel#1]
Is Python 3.6 supported? If not, what is the concrete plan for supporting it? As a reminder, Python 2 is a mere 1.5 years from expiration, so it doesn't even make sense to spend a single second on it.

**Comment by twintechlabs** [comment]
Python 3.6 is now supported. When I first started the project (in a form that looked nothing like this), some of the underlying machine learning libraries that I used only supported Python 2. That's since been remedied and ioModel supports Python 3 now as well.
